DROP VIEW VIEW_MoneyAmounts
GO

CREATE VIEW VIEW_MoneyAmounts AS

select 1 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 2 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'PERFORMACE ADJUSTMENT' as rightName,1 as montoPercibido UNION 
select 3 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 2 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 4 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 3 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 5 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 6 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'PERFORMACE ADJUSTMENT' as rightName,1 as montoPercibido UNION 
select 7 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 2 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 8 as id, 14778 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 3 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 9 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 10 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'PERFORMACE ADJUSTMENT' as rightName,1 as montoPercibido UNION 
select 11 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 2 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 12 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 3 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 13 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 14 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'PERFORMACE ADJUSTMENT' as rightName,1 as montoPercibido UNION 
select 15 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 2 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 16 as id, 14778 as companyId, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 3 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 17 as id, 1 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 18 as id, 1 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 1 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'PERFORMACE ADJUSTMENT' as rightName,1 as montoPercibido UNION 
select 19 as id, 1 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 2 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido UNION 
select 20 as id, 1 as companyId, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 3 as trimestre,4831447 as idCancion, 'SIN ALIENTO' as nombreCancion, 4349894 as idAutor, 'ROFFIEL DEL RIO, ROBERTO RICARDO' as nombreAutor, 61 as idFuente, 'SADAIC' as nombreFuente, 'OPEN TELEVISION' as rightName,1 as montoPercibido
GO

DROP VIEW VIEW_Units
GO

CREATE VIEW VIEW_Units AS
select 1 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 2 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'OPEN TELEVISION' as rightName,1 as cantidadUnidades UNION 
select 3 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 2 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 4 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2013 as anio, 3 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 5 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 6 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'OPEN TELEVISION' as rightName,1 as cantidadUnidades UNION 
select 7 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 2 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 8 as id, 38 as idPais, 'COLOMBIA' as nombrePais, 2012 as anio, 3 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 9 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 10 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'OPEN TELEVISION' as rightName,1 as cantidadUnidades UNION 
select 11 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 2 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 12 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2013 as anio, 3 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 13 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 14 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 1 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'OPEN TELEVISION' as rightName,1 as cantidadUnidades UNION 
select 15 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 2 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades UNION 
select 16 as id, 7 as idPais, 'ARGENTINA' as nombrePais, 2012 as anio, 3 as trimestre,4831658 as idCancion, 'AMOR GITANO' as nombreCancion, 4350113 as idAutor, 'FLORES MONTERRUBIO, JAIME' as nombreAutor, 'GENERAL RADIO' as rightName,1 as cantidadUnidades 
